export const GET_LIVE_COMMENTARY = 'GET_LIVE_COMMENTARY';
export const GET_LIVE_COMMENTARY_SUCCESS = 'GET_LIVE_COMMENTARY_SUCCESS';
export const GET_LIVE_COMMENTARY_ERROR = 'GET_LIVE_COMMENTARY_ERROR';
